<?php

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data =
            [
                [
                    'title' => 'Trang chủ',
                    'slug' => 'trang-chu',
                    'sort' => 0,
                    'admin_id' => 1,
                    'parent_id' => null,
                    'type' => '',
                    'status' => 1,
                    'created_at' => date("Y/m/d H:i:s"),
                    'updated_at' => date("Y/m/d H:i:s"),
                ],
                [
                    'title' => 'Tìm giá tốt',
                    'slug' => 'tim-gia-tot',
                    'sort' => 1,
                    'admin_id' => 1,
                    'parent_id' => null,
                    'type' => 'product',
                    'status' => 1,
                    'created_at' => date("Y/m/d H:i:s"),
                    'updated_at' => date("Y/m/d H:i:s"),
                ],
                [
                    'title' => 'Kiến thức',
                    'slug' => 'kien-thuc',
                    'sort' => 2,
                    'admin_id' => 1,
                    'parent_id' => null,
                    'type' => 'new',
                    'status' => 1,
                    'created_at' => date("Y/m/d H:i:s"),
                    'updated_at' => date("Y/m/d H:i:s"),
                ],
                [
                    'title' => 'Tin tức',
                    'slug' => 'tin-tuc',
                    'sort' => 3,
                    'admin_id' => 1,
                    'parent_id' => null,
                    'type' => 'new',
                    'status' => 1,
                    'created_at' => date("Y/m/d H:i:s"),
                    'updated_at' => date("Y/m/d H:i:s"),
                ],
                [
                    'title' => 'Đối tác',
                    'slug' => 'doi-tac',
                    'sort' => 4,
                    'admin_id' => 1,
                    'parent_id' => null,
                    'type' => 'new',
                    'status' => 1,
                    'created_at' => date("Y/m/d H:i:s"),
                    'updated_at' => date("Y/m/d H:i:s"),
                ],
                [
                    'title' => 'Thiết bị camera',
                    'slug' => 'thiet-bi-camera',
                    'sort' => 5,
                    'admin_id' => 1,
                    'parent_id' => null,
                    'url' => 'https://cameravn247.com/dich-vu-lap-dat-camera.html',
                    'type' => 'link',
                    'status' => 1,
                    'created_at' => date("Y/m/d H:i:s"),
                    'updated_at' => date("Y/m/d H:i:s"),
                ],
                [
                    'title' => 'Thiết bị website',
                    'slug' => 'thiet-bi-website',
                    'sort' => 6,
                    'admin_id' => 1,
                    'parent_id' => null,
                    'url' => 'https://web89.vn/',
                    'type' => 'link',
                    'status' => 1,
                    'created_at' => date("Y/m/d H:i:s"),
                    'updated_at' => date("Y/m/d H:i:s"),
                ],

                //parent timgiatot
                [
                    'title' => 'Nhà cửa – Đời sống',
                    'slug' => 'nha-cua-doi-song',
                    'sort' => 0,
                    'admin_id' => 1,
                    'parent_id' => 2,
                    'type' => 'product',
                    'status' => 1,
                    'created_at' => date("Y/m/d H:i:s"),
                    'updated_at' => date("Y/m/d H:i:s"),
                ],
                    [
                        'title' => 'Đèn sưởi',
                        'slug' => 'den-suoi',
                        'sort' => 0,
                        'admin_id' => 1,
                        'parent_id' => 8,
                        'type' => 'product',
                        'status' => 1,
                        'created_at' => date("Y/m/d H:i:s"),
                        'updated_at' => date("Y/m/d H:i:s"),
                    ],
                [
                    'title' => 'Thiết bị an ninh',
                    'slug' => 'thiet-bi-an-ninh',
                    'sort' => 1,
                    'admin_id' => 1,
                    'parent_id' => 2,
                    'type' => 'product',
                    'status' => 1,
                    'created_at' => date("Y/m/d H:i:s"),
                    'updated_at' => date("Y/m/d H:i:s"),
                ],
                    [
                        'title' => 'Bộ camera giám sát',
                        'slug' => 'bo-camera-giam-sat',
                        'sort' => 0,
                        'admin_id' => 1,
                        'parent_id' => 10,
                        'type' => 'product',
                        'status' => 1,
                        'created_at' => date("Y/m/d H:i:s"),
                        'updated_at' => date("Y/m/d H:i:s"),
                    ],
                    [
                        'title' => 'Camera wifi',
                        'slug' => 'camera-wifi',
                        'sort' => 1,
                        'admin_id' => 1,
                        'parent_id' => 10,
                        'type' => 'product',
                        'status' => 1,
                        'created_at' => date("Y/m/d H:i:s"),
                        'updated_at' => date("Y/m/d H:i:s"),
                    ],
                    [
                        'title' => 'Đầu ghi hình camera',
                        'slug' => 'dau-ghi-hinh-camera',
                        'sort' => 2,
                        'admin_id' => 1,
                        'parent_id' => 10,
                        'type' => 'product',
                        'status' => 1,
                        'created_at' => date("Y/m/d H:i:s"),
                        'updated_at' => date("Y/m/d H:i:s"),
                    ],
                    [
                        'title' => 'Phụ kiện camera',
                        'slug' => 'phu-kien-camera',
                        'sort' => 3,
                        'admin_id' => 1,
                        'parent_id' => 10,
                        'type' => 'product',
                        'status' => 1,
                        'created_at' => date("Y/m/d H:i:s"),
                        'updated_at' => date("Y/m/d H:i:s"),
                    ],
                [
                    'title' => 'Thiết bị điện tử',
                    'slug' => 'thiet-bi-dien-tu',
                    'sort' => 2,
                    'admin_id' => 1,
                    'parent_id' => 2,
                    'type' => 'product',
                    'status' => 1,
                    'created_at' => date("Y/m/d H:i:s"),
                    'updated_at' => date("Y/m/d H:i:s"),
                ],
                [
                    'title' => 'Thiết bị gia đình',
                    'slug' => 'thiet-bi-gia-dinh',
                    'sort' => 3,
                    'admin_id' => 1,
                    'parent_id' => 2,
                    'type' => 'product',
                    'status' => 1,
                    'created_at' => date("Y/m/d H:i:s"),
                    'updated_at' => date("Y/m/d H:i:s"),
                ],
                [
                    'title' => 'Thiết bị nhà bếp',
                    'slug' => 'thiet-bi-nha-bep',
                    'sort' => 4,
                    'admin_id' => 1,
                    'parent_id' => 2,
                    'type' => 'product',
                    'status' => 1,
                    'created_at' => date("Y/m/d H:i:s"),
                    'updated_at' => date("Y/m/d H:i:s"),
                ],
                [
                    'title' => 'Thiết bị văn phòng',
                    'slug' => 'thiet-bi-van-phong',
                    'sort' => 5,
                    'admin_id' => 1,
                    'parent_id' => 2,
                    'type' => 'product',
                    'status' => 1,
                    'created_at' => date("Y/m/d H:i:s"),
                    'updated_at' => date("Y/m/d H:i:s"),
                ],
                [
                    'title' => 'Thiết bị công nghiệp',
                    'slug' => 'thiet-bi-cong-nghiep',
                    'sort' => 6,
                    'admin_id' => 1,
                    'parent_id' => 2,
                    'type' => 'product',
                    'status' => 1,
                    'created_at' => date("Y/m/d H:i:s"),
                    'updated_at' => date("Y/m/d H:i:s"),
                ],

                //tin tuc
                [
                    'title' => 'Tin khuyến mãi',
                    'slug' => 'tin-khuyen-mai',
                    'sort' =>   0,
                    'admin_id' => 1,
                    'parent_id' => 4,
                    'type' => 'new',
                    'status' => 1,
                    'created_at' => date("Y/m/d H:i:s"),
                    'updated_at' => date("Y/m/d H:i:s"),
                ]
            ];
        foreach ($data as $row){
            $row['slug'] = \Illuminate\Support\Str::slug($row['title'], '-');
            DB::table('categories')->insert($row);
        }

    }
}
